version: '3'
services:
  postgres:
    image: postgres:alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: "guacamole_db"
      POSTGRES_USER: "guacamole_usr"
      POSTGRES_PASSWORD: "guacamole_pass"
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
      - ./postgres:/var/lib/postgresql/data
  
  guacd:
    image: guacamole/guacd
    restart: unless-stopped
  
  guacamole:
    image: guacamole/guacamole
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      GUACD_HOSTNAME: guacd
      POSTGRES_HOSTNAME: postgres
      POSTGRES_DATABASE: "guacamole_db"
      POSTGRES_USER: "guacamole_usr"
      POSTGRES_PASSWORD: "guacamole_pass"

  chrome:
    image: selenium/standalone-chrome-debug
    restart: unless-stopped

  firefox:
    image: selenium/standalone-firefox-debug
    restart: unless-stopped
